name: mobEras
description: Protocolo mobEras

version: 0.1.8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  video_player: 0.10.11+1
  # state management
  stacked: ^1.7.6
  stacked_hooks: 0.1.3

  # navigation
  get: ^3.4.6
  auto_route: ^0.6.9
  stacked_services: ^0.5.2
  rxdart: ^0.24.1

  # inversion of control
  get_it: ^4.0.4
  injectable: ^1.0.5
  flutter_hooks: ^0.12.0
  observable_ish: ^2.1.4
  location: ^3.0.2
  jiffy: ^3.0.1
  connectivity: ^0.4.8+6


  # firebase INI
  cloud_functions: ^0.5.0
  cloud_firestore: ^0.13.7
  firebase_analytics: ^5.0.16
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_crashlytics: ^0.1.4+1
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.6

  google_fonts: ^1.1.0
  intl: ^0.16.1
  string_validator: ^0.1.4
  cached_network_image: ^2.2.0+1
  logger: ^0.9.2
  json_annotation: ^3.0.1
  quiver: ^2.1.3
  mask_text_input_formatter: ^1.1.0
  flutter_datetime_picker: ^1.3.8
  pedometer: ^2.0.2
  lottie: ^0.6.0
  cpf_cnpj_validator: ^1.0.5
  chewie: ^0.9.10
  flutter_xlider: ^3.4.0
  datetime_picker_formfield: ^1.0.0
  diacritic: ^0.1.1
  flutter_date_pickers: ^0.1.7
  marquee: ^1.6.1
  auto_size_text: ^2.1.0
  flutter_form_builder: ^3.14.0
  flutter_beep: ^0.2.0
  assets_audio_player: ^2.0.13+1
  flutter_local_notifications: ^3.0.2
  bringtoforeground: ^0.0.2
  android_alarm_manager: ">=0.4.5+7 <2.0.0"
  screen: ^0.0.5




dev_dependencies:
  mockito: ^4.1.1
  build_runner: ^1.10.3
  auto_route_generator: ^0.6.10
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/app_icon.png
    - assets/lang/en.json
    - assets/lang/pt.json
    - assets/images/
    - assets/images/scale/
    - assets/images/scale/drink_eat/
    - assets/images/scale/nausea/
    - assets/images/scale/pain/
    - assets/images/scale/urine/
    - assets/images/scale/well_being/
    - assets/images/scale/yes_no/
    - assets/videos/MobERAScurto.mp4
    - assets/images/scale/pain/zerototen.png
    - assets/icons/smile.svg
    - assets/lotties/
    - assets/audio/
scripts:
  buildRunner: flutter pub run build_runner build --delete-conflicting-outputs
